name: Build and test SwiftGdk

# Dependencies of this package
env:
  MACOS_BREW: ${{ 'gtk+3 pango glib glib-networking gobject-introspection pkg-config jq' }}
  UBUNTU_APT: ${{ 'libgtk-3-dev gir1.2-gtk-3.0 gir1.2-gtksource-3.0 libpango1.0-dev gir1.2-pango-1.0 libglib2.0-dev glib-networking gobject-introspection libgirepository1.0-dev libxml2-dev jq' }}

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  # macOS tasks
  build-mac-swift-latest:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.2'

      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: brew install $MACOS_BREW

      - name: Checkout SwiftGdk
        uses: actions/checkout@v2
        with:
          path: SwiftGdk

      - name: Build Swift Wrappers
        run: |
          cd SwiftGdk
          ./run-gir2swift.sh
          echo "GIR2SWIFT_PATH=${PWD}/checkouts/gir2swift/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Build SwiftGdk
        run: |
          cd SwiftGdk
          swift build `./run-gir2swift.sh flags -noUpdate`
          cd ..

      - name: Test SwiftGdk
        run: |
          cd SwiftGdk
          swift test `./run-gir2swift.sh flags -noUpdate`
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: | 
          cd SwiftGdk
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-macos
          path: |
            SwiftGdk/
          retention-days: 1

  # Ubuntu 20.04 tasks
  build-ubuntu-20_04-swift-latest:
    runs-on: ubuntu-20.04
    steps:
      - name: Print Swift version to confirm
        run: swift --version
      - name: Fetch dependencies for general repository
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout SwiftGdk
        uses: actions/checkout@v2
        with:
          path: SwiftGdk

      - name: Build current SwiftGdk
        run: |
          cd SwiftGdk
          ./run-gir2swift.sh
          echo "GIR2SWIFT_PATH=${PWD}/checkouts/gir2swift/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Build SwiftGdk
        run: |
          cd SwiftGdk
          swift build
          cd ..

      - name: Test SwiftGdk
        run: |
          cd SwiftGdk
          swift test
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: | 
          cd SwiftGdk
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-20.04-5.3
          path: |
            SwiftGdk/
          retention-days: 1

  # Ubuntu 18.04 tasks
  build-ubuntu-18_04-swift-latest:
    runs-on: ubuntu-18.04
    steps:
      - name: Print Swift version to confirm
        run: swift --version
      - name: Fetch dependencies for general repository
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout SwiftGdk
        uses: actions/checkout@v2
        with:
          path: SwiftGdk

      - name: Build current SwiftGdk
        run: |
          cd SwiftGdk
          ./run-gir2swift.sh
          echo "GIR2SWIFT_PATH=${PWD}/checkouts/gir2swift/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Build SwiftGdk
        run: |
          cd SwiftGdk
          swift build
          cd ..

      - name: Test SwiftGdk
        run: |
          cd SwiftGdk
          swift test
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: |
          cd SwiftGdk
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-18.04-5.3
          path: |
            SwiftGdk/
          retention-days: 1
